;; Automatically generated by private/make-aliased-libraries.sps
#!r6rs
(library (_srfi :6)
  (export
    get-output-string
    open-input-string
    open-output-string)
  (import (_srfi :6 basic-string-ports))
)
